### PR TITLE
Store settings instance in the Microframework instance, so that it is accessible at the end. 

### PR DESCRIPTION
**Pull request by hirsch88**
Hi,

I want to use supertest for my e2e testing and for that I need the express application. I tried to access the express app after the bootstrap process, but unfortunately the settings object was not the one from the loaders. 

So I replace the local const with the settings form the class. This solve my problem.

### CODE REVIEW

**Comment by hirsch88** [comment]
#5 should be fixed with this pr

**Comment by hirsch88** [comment]
Hi,
I published my changes on npm([microframework-w3tec](https://www.npmjs.com/package/microframework-w3tec)), because I couldn't wait for it. :-)

However, I will change back to your project when the pr or another solution has been published.
Cheers,
hirsch88

**Comment by mlaflamm** [comment]
@pleerock any chance that you merge this PR and publish to npm? Thank you.

**Comment by nolazybits** [comment]
@pleerock keen on this too. Thanks :)

**Comment by NoNameProvided** [comment]
Closing as this project is being deprecated.

**Pull request closed without merging**
